import { Type, type Static, type TSchema } from "typebox";

const integer = Type.Integer();
const number = Type.Number();
const boolean = Type.Boolean();
const text = Type.String();
const nullableText = Type.Union([text, Type.Null()]);

function nullable<T extends TSchema>(schema: T) {
  return Type.Union([schema, Type.Null()]);
}

const enumValue = Type.Object({ value: integer, name: text });
const canonicalReference = Type.Object({
  nativeId: integer,
  name: nullableText,
  internalName: nullableText,
  fileName: nullableText,
});
const sceneEvidence = Type.Object({
  nativeId: nullable(integer),
  nativeIdMatched: boolean,
  nativeIdMatchBasis: nullableText,
  name: nullableText,
  path: nullableText,
  buildIndex: integer,
  handle: integer,
});
const hierarchyNode = Type.Object({ name: text, siblingIndex: integer });
const sourceDetails = Type.Object({
  hierarchyPath: nullableText,
  hierarchyNodes: Type.Array(hierarchyNode),
  hierarchyDepth: Type.Optional(integer),
  hierarchyPathTruncated: Type.Optional(boolean),
  componentType: text,
  componentIndex: integer,
  observationIndex: integer,
  saverIdentifier: Type.Optional(nullableText),
  saverIdentifierError: Type.Optional(nullableText),
  addressableAssetGuid: Type.Optional(nullableText),
  addressableAssetGuidError: Type.Optional(nullableText),
});
const sourceIdentity = Type.Object({
  status: text,
  provenStable: boolean,
  hierarchyPathCandidate: nullableText,
  saverIdentifierCandidate: nullableText,
  addressableAssetGuidCandidate: nullableText,
});
const sourceEvidence = Type.Object({
  componentInstanceId: nullable(integer),
  gameObjectInstanceId: nullable(integer),
  sourceScene: nullable(sceneEvidence),
  source: sourceDetails,
  sourceIdentity,
  position: Type.Object({ x: number, y: number, z: number }),
  activeSelf: boolean,
  activeInHierarchy: boolean,
  enabled: boolean,
});

const timeRequirement = Type.Object({
  checkYear: boolean,
  checkMonth: boolean,
  checkWeek: boolean,
  checkDay: boolean,
  checkHour: boolean,
  checkMinute: boolean,
  checkSecond: boolean,
  checkGlobalSpeed: boolean,
  year: integer,
  month: integer,
  week: integer,
  day: integer,
  hour: integer,
  minute: integer,
  second: integer,
  globalSpeed: integer,
});
const projectedReference = nullable(canonicalReference);
const conditionRequirement = Type.Object({
  sourceFieldPath: text,
  groupIndex: integer,
  requirementIndex: integer,
  requirementType: text,
  requirementTypeValue: integer,
  conditionRule: text,
  conditionRuleValue: integer,
  evaluation: text,
  abilityID: integer,
  bonusID: integer,
  recipeID: integer,
  resourceID: integer,
  effectID: integer,
  NPCID: integer,
  statID: integer,
  factionID: integer,
  comboID: integer,
  raceID: integer,
  levelsID: integer,
  classID: integer,
  speciesID: integer,
  itemID: integer,
  currencyID: integer,
  pointID: integer,
  talentTreeID: integer,
  skillID: integer,
  spellbookID: integer,
  weaponTemplateID: integer,
  enchantmentID: integer,
  gearSetID: integer,
  gameSceneID: integer,
  questID: integer,
  dialogueID: integer,
  knowledge: enumValue,
  state: enumValue,
  comparison: enumValue,
  value: enumValue,
  ownership: enumValue,
  itemCondition: enumValue,
  progression: enumValue,
  entity: enumValue,
  pointType: enumValue,
  dialogueNodeState: enumValue,
  effectCondition: enumValue,
  amountType: enumValue,
  timeType: enumValue,
  timeValue: enumValue,
  amount1: number,
  amount2: number,
  float1: number,
  consume: boolean,
  boolBalue1: boolean,
  boolBalue2: boolean,
  boolBalue3: boolean,
  isPercent: boolean,
  effectTag: projectedReference,
  effectType: enumValue,
  factionStance: projectedReference,
  itemType: projectedReference,
  weaponType: projectedReference,
  weaponSlot: projectedReference,
  armorType: projectedReference,
  armorSlot: projectedReference,
  gender: projectedReference,
  questState: enumValue,
  dialogueNode: nullable(Type.Object({ nativeType: text, text })),
  NPCFamily: projectedReference,
  region: projectedReference,
  timeRequirement1: nullable(timeRequirement),
  timeRequirement2: nullable(timeRequirement),
});
const requirementRow = Type.Union([conditionRequirement, Type.Null()]);
const requirementGroup = Type.Union([
  Type.Object({
    sourceFieldPath: text,
    groupIndex: integer,
    checkCount: boolean,
    requiredCount: integer,
    nativeRequirementCount: integer,
    requirements: Type.Array(requirementRow),
  }),
  Type.Null(),
]);
const requirementTemplate = nullable(Type.Object({
  nativeId: integer,
  sourceName: text,
  name: nullableText,
  internalName: nullableText,
  fileName: nullableText,
  description: nullableText,
  nativeType: text,
  nativeGroupCount: integer,
  sourceFieldPath: text,
  groups: Type.Array(requirementGroup),
}));

const actionUnavailable = Type.Object({ sourceFieldPath: text, unavailable: text });
// Set when a referenced RPGEffect is of type Teleport: the door's destination, exact to the
// authored teleportPOS for both gameScene and position teleports.
const effectTeleport = nullable(Type.Object({
  sourceFieldPath: text,
  rankCount: integer,
  type: enumValue,
  sceneNativeId: integer,
  destinationScene: nullable(Type.Object({ nativeId: integer, name: nullableText, internalName: nullableText, fileName: nullableText })),
  position: Type.Object({ x: number, y: number, z: number }),
}));
const gameActionTeleport = nullable(Type.Object({
  type: enumValue,
  sceneNativeId: integer,
  position: Type.Object({ x: number, y: number, z: number }),
  rotation: Type.Object({ x: number, y: number, z: number }),
}));
const gameAction = Type.Object({
  sourceFieldPath: text,
  sourceIndex: integer,
  type: enumValue,
  chance: number,
  nativeRequirementGroupCount: integer,
  requirements: Type.Array(requirementGroup),
  teleport: gameActionTeleport,
  lootTableID: nullable(integer),
  lootTable: projectedReference,
  effectID: nullable(integer),
  effect: projectedReference,
  effectTeleport: effectTeleport,
  unsupported: boolean,
});
const gameActionRow = Type.Union([gameAction, actionUnavailable]);
const gameActionList = Type.Object({
  available: boolean,
  nativeActionCount: integer,
  actions: Type.Array(gameActionRow),
});
const gameActions = Type.Object({
  executionOrder: Type.Literal("template-then-inline"),
  template: nullable(Type.Object({
    instanceId: integer,
    nativeId: integer,
    name: nullableText,
    internalName: nullableText,
    fileName: nullableText,
    available: boolean,
    nativeActionCount: integer,
    actions: Type.Array(gameActionRow),
  })),
  inline: gameActionList,
});
const action = Type.Object({
  sourceFieldPath: text,
  type: enumValue,
  activationType: enumValue,
  chance: number,
  chanceSemantics: text,
  entryID: integer,
  amount: number,
  referenceKind: nullableText,
  referenceId: nullable(integer),
  reference: projectedReference,
  effect: projectedReference,
  effectTeleport: effectTeleport,
  quest: projectedReference,
  point: projectedReference,
  skill: projectedReference,
  weaponTemplate: projectedReference,
  task: projectedReference,
  resource: projectedReference,
  lootTable: projectedReference,
  gameActions: gameActions,
  unityEventAvailable: boolean,
  unsupported: boolean,
});
const actionRow = Type.Union([action, actionUnavailable]);
const chestLootRow = Type.Union([
  Type.Object({
    sourceFieldPath: text,
    itemID: nullable(integer),
    item: projectedReference,
    itemReferenceStatus: text,
    minCount: integer,
    maxCount: integer,
    quantitySemantics: text,
    dropChance: number,
    dropChanceSemantics: text,
    lootedObservation: boolean,
  }),
  actionUnavailable,
]);
const chestLootProjection = Type.Object({
  sourceFieldPath: text,
  lootInstancesAvailable: boolean,
  lootInstanceCount: integer,
  lootInstances: Type.Array(chestLootRow),
  maxDrops: integer,
  maxDropsSemantics: text,
  interactionDistance: number,
  chestName: nullableText,
});

const candidateInteractable = Type.Union([
  Type.Object({
    source: sourceEvidence,
    authoredOnly: boolean,
    state: enumValue,
    interactableName: nullableText,
    actions: Type.Array(actionRow),
    requirementsTemplate: requirementTemplate,
    requirementsOwner: nullable(Type.Object({ ownerKind: text, sourceFieldPath: text, source: sourceEvidence })),
    resource: projectedReference,
    resourceUseValues: boolean,
    lootWindowGathering: boolean,
    limitedUseAmount: boolean,
    maxUseAmount: number,
    maxActions: integer,
    cooldown: number,
    interactionTime: number,
    maxDistance: number,
    isTrigger: boolean,
    isClick: boolean,
  }),
  actionUnavailable,
]);
const candidateChest = Type.Union([
  Type.Object({ source: sourceEvidence, authoredOnly: boolean, loot: chestLootProjection }),
  actionUnavailable,
]);
const candidateOutput = Type.Object({
  outputKind: text,
  sourceFieldPath: text,
  resourceID: Type.Optional(nullable(integer)),
  resource: Type.Optional(projectedReference),
  lootTableID: Type.Optional(nullable(integer)),
  lootTable: Type.Optional(projectedReference),
  source: Type.Optional(sourceEvidence),
  loot: Type.Optional(chestLootProjection),
  authoredActionChance: Type.Optional(number),
  effectiveProbabilityResolved: boolean,
  outputSemantics: Type.Optional(text),
});
const possibleOutput = Type.Object({ optionIndex: integer, output: candidateOutput });
const candidateOption = Type.Union([
  Type.Object({
    sourceFieldPath: text,
    optionIndex: integer,
    veinPrefab: nullable(Type.Object({ name: text })),
    requiredSkill: integer,
    weightAtLowSkill: number,
    weightAtHighSkill: number,
    teaserWeight: number,
    authoredInteractables: Type.Array(candidateInteractable),
    authoredChests: Type.Array(candidateChest),
    possibleOutputs: Type.Array(candidateOutput),
    candidateInspection: Type.Object({ instantiated: boolean, rolled: boolean, mutated: boolean }),
  }),
  actionUnavailable,
]);
const weightSample = Type.Union([
  Type.Object({ sourceFieldPath: text, skill: integer, weights: Type.Array(number), semantics: text }),
  actionUnavailable,
]);
const currentNodeObservation = Type.Union([
  Type.Object({
    present: Type.Literal(true),
    observationKind: Type.Literal("runtimeGeneratedInstance"),
    instanceIdObservation: integer,
    source: sourceEvidence,
    interactableName: nullableText,
    state: enumValue,
  }),
  Type.Object({
    present: Type.Literal(false),
    observationKind: Type.Literal("runtimeGeneratedInstance"),
    reason: Type.Optional(text),
    unavailable: Type.Optional(text),
  }),
]);
const oreSpawner = Type.Union([
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    producerFamily: text,
    role: text,
    roles: Type.Array(text),
    sourceIndex: integer,
    miningSkillID: integer,
    gatheringSkillID: nullable(integer),
    gatheringSkill: projectedReference,
    gatheringRole: Type.Object({ kind: text, skillID: nullable(integer), skill: projectedReference, sourceFieldPath: text, semantics: text }),
    resourceNode: Type.Optional(projectedReference),
    projection: Type.Optional(Type.Object({})),
    skillCap: number,
    respawnTime: number,
    respawnJitter: number,
    despawnDelay: number,
    playerRange: number,
    optionsAvailable: boolean,
    optionCount: integer,
    options: Type.Array(candidateOption),
    possibleOutputsAvailable: boolean,
    possibleOutputCount: integer,
    possibleOutputs: Type.Array(possibleOutput),
    outputSemantics: text,
    computeWeightsSamples: Type.Array(weightSample),
    currentNodeObservation,
    authoredProducerIndependentOfObservation: boolean,
  }),
  Type.Object({ sourceIndex: integer, producerFamily: text, unavailable: text }),
]);

const nodeChance = { sourceFieldPath: text, chance: number, chanceSemantics: text };
const nodeContainerRow = Type.Union([actionUnavailable, Type.Object({ ...nodeChance, lootTableID: nullable(integer), lootTable: projectedReference })]);
const nodeProjection = Type.Object({
  source: sourceEvidence,
  disposition: text,
  producerFamily: Type.Literal("interactiveNode"),
  nodeType: enumValue,
  nodeStateObservation: Type.Object({ value: integer, name: text, useCount: integer, nextUse: number }),
  interactableName: nullableText,
  isTrigger: boolean,
  isClick: boolean,
  gatherSkill: projectedReference,
  gatherSkillID: nullable(integer),
  gatherExperience: number,
  gatheringRole: Type.Object({ kind: text, skillID: nullable(integer), skill: projectedReference, sourceFieldPath: text, semantics: text }),
  resourceNode: projectedReference,
  resourceNodeProjected: projectedReference,
  possibleOutputs: Type.Object({
    resourceRanks: nullable(Type.Object({ available: boolean, count: integer, resource: projectedReference })),
    containerLootTables: nullable(Type.Array(nodeContainerRow)),
  }),
  containerTablesDataAvailable: boolean,
  containerTableCount: integer,
  containerTablesData: Type.Array(nodeContainerRow),
  effectsDataAvailable: boolean,
  effectCount: integer,
  effectsData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, effectID: nullable(integer), effect: projectedReference })])),
  questsDataAvailable: boolean,
  questsData: Type.Array(Type.Object({ ...nodeChance, questID: nullable(integer), quest: projectedReference })),
  skillsDataAvailable: boolean,
  skillCount: integer,
  skillsData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, skillID: nullable(integer), skill: projectedReference })])),
  abilitiesData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, abilityID: nullable(integer), ability: projectedReference })])),
  abilityCount: integer,
  treePointsData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, treePointID: nullable(integer), treePoint: projectedReference, amount: number })])),
  treePointCount: integer,
  skillExpData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, skillID: nullable(integer), skill: projectedReference, expAmount: number })])),
  skillExperienceCount: integer,
  taskData: Type.Array(Type.Union([actionUnavailable, Type.Object({ ...nodeChance, taskID: nullable(integer), task: projectedReference })])),
  taskCount: integer,
  classExperience: nullable(Type.Object({ expAmount: number, chance: number, chanceSemantics: text })),
  unsupportedUnityEvent: boolean,
  nodeRoles: Type.Object({ resource: boolean, container: boolean }),
});
const resourceProducer = Type.Union([
  oreSpawner,
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    producerFamily: Type.Literal("interactiveNode"),
    role: text,
    roles: Type.Array(text),
    sourceIndex: integer,
    gatheringSkillID: nullable(integer),
    gatheringSkill: projectedReference,
    gatheringRole: Type.Object({ kind: text, skillID: nullable(integer), skill: projectedReference, sourceFieldPath: text, semantics: text }),
    resourceNode: projectedReference,
    projection: nodeProjection,
    authoredProducerIndependentOfObservation: boolean,
  }),
]);
const interaction = Type.Union([
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    family: text,
    role: text,
    roles: Type.Array(text),
    roleSource: text,
    interactableName: nullableText,
    state: enumValue,
    actionsAvailable: boolean,
    actionCount: integer,
    actions: Type.Array(actionRow),
    requirementsTemplate: requirementTemplate,
    requirementsOwner: nullable(Type.Object({ ownerKind: text, sourceFieldPath: text, source: sourceEvidence })),
    resource: projectedReference,
    resourceID: nullable(integer),
    isPersistent: boolean,
    isTrigger: boolean,
    isClick: boolean,
    limitedUseAmount: boolean,
    maxUseAmount: number,
    maxActions: integer,
    cooldown: number,
    interactionTime: number,
    maxDistance: number,
    lootWindowGathering: boolean,
    allowNPCInteraction: boolean,
    requiredNPCRanksAvailable: boolean,
    requiredNPCRankCount: integer,
    requiredNPCRanks: Type.Array(nullableText),
  }),
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    family: Type.Literal("interactableTrigger"),
    role: text,
    roles: Type.Array(text),
    roleSource: text,
    state: enumValue,
    triggerTag: nullableText,
    cooldown: number,
    actionsAvailable: boolean,
    actionCount: integer,
    actions: Type.Array(actionRow),
  }),
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    family: Type.Literal("chest"),
    role: text,
    roles: Type.Array(text),
    roleSource: text,
    interactableName: nullableText,
    projection: chestLootProjection,
  }),
  Type.Object({
    source: sourceEvidence,
    disposition: text,
    family: Type.Literal("interactiveNode"),
    role: text,
    roleEvidence: Type.Object({ resource: boolean, container: boolean, sourceRule: text }),
    projection: nodeProjection,
  }),
]);
const container = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: text,
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  chestName: Type.Optional(nullableText),
  projection: Type.Union([chestLootProjection, nodeProjection]),
  interaction: Type.Optional(Type.Object({ interactionDistance: number, maxDrops: integer })),
});
// ContainerObject: player storage, without loot.
const storageContainer = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: Type.Literal("storageContainer"),
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  interactableName: nullableText,
  slotAmount: integer,
  isClick: boolean,
  maxDistance: number,
  uiOffsetY: number,
  requirementsTemplate: requirementTemplate,
});

const worldQuestReference = Type.Object({
  nativeId: integer,
  name: nullableText,
  internalName: nullableText,
  fileName: nullableText,
  quest: Type.Optional(projectedReference),
  availableDuration: Type.Optional(number),
  cooldownAfterExpiry: Type.Optional(number),
  cooldownAfterCompletion: Type.Optional(number),
  cooldownRandomJitter: Type.Optional(number),
  initialRollWindow: Type.Optional(number),
});
const questPoolRow = Type.Union([
  Type.Object({ sourceFieldPath: text, worldQuest: worldQuestReference }),
  actionUnavailable,
]);
const currentQuestObservation = Type.Union([
  Type.Object({ present: Type.Literal(false) }),
  Type.Object({ present: Type.Literal(true), worldQuest: worldQuestReference }),
  Type.Object({ present: Type.Literal(false), unavailable: text }),
]);
const questZone = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: Type.Literal("worldQuestZone"),
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  selectionRule: text,
  worldQuest: nullable(worldQuestReference),
  possibleQuestsAvailable: boolean,
  possibleQuestCount: integer,
  possibleQuests: Type.Array(questPoolRow),
  zoneRespawnCooldown: number,
  currentQuestObservation,
});

const transition = Type.Object({
  source: sourceEvidence,
  disposition: text,
  transitionKind: text,
  role: Type.Literal("transition"),
  roles: Type.Array(text),
  roleSource: text,
  destinationSceneName: nullableText,
  destinationScene: nullable(canonicalReference),
  destinationReferenceStatus: text,
  destinationResolved: boolean,
});
const craftSkill = Type.Union([
  Type.Object({ sourceFieldPath: text, craftSkillID: integer, craftSkill: projectedReference, referenceStatus: text }),
  actionUnavailable,
]);
const craftingService = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: Type.Literal("craftingStation"),
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  stationID: nullable(integer),
  station: projectedReference,
  stationReferenceStatus: text,
  useDistanceMax: number,
  interactableUIoffsetY: number,
  craftSkillsAvailable: boolean,
  craftSkillCount: integer,
  craftSkills: Type.Array(craftSkill),
});
const propertyService = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: Type.Literal("propertyForSaleSign"),
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  propertyID: nullable(integer),
  property: projectedReference,
  propertyReferenceStatus: text,
  propertyType: enumValue,
  currencyID: nullable(integer),
  currency: projectedReference,
  currencyReferenceStatus: text,
  purchasePrice: nullable(integer),
  sellPrice: nullable(integer),
  incomeAmount: nullable(integer),
  maxInteractionDistance: number,
  uiOffsetY: number,
  signVisualObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
});
const altarService = Type.Object({
  source: sourceEvidence,
  disposition: text,
  family: Type.Literal("corruptionAltar"),
  role: text,
  roles: Type.Array(text),
  roleSource: text,
  altarName: nullableText,
  countdownFromNumber: integer,
  maxInteractionDistance: number,
  uiOffsetY: number,
  barrierObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
  consumedVisualObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
});
const service = Type.Union([craftingService, propertyService, altarService]);

const conditionCommon = {
  source: sourceEvidence,
  disposition: text,
  family: text,
  conditionKind: text,
  semantics: text,
};
const classEligibility = Type.Union([
  Type.Object({ sourceFieldPath: text, classID: integer, classReference: projectedReference, referenceStatus: text }),
  actionUnavailable,
]);
const raceEligibility = Type.Union([
  Type.Object({ sourceFieldPath: text, raceID: integer, race: projectedReference, referenceStatus: text }),
  actionUnavailable,
]);
const conditionSource = Type.Union([
  Type.Object({
    ...conditionCommon,
    family: Type.Literal("characterGraveyard"),
    requiredClassesAvailable: boolean,
    requiredClassCount: integer,
    requiredClasses: Type.Array(classEligibility),
    requiredRacesAvailable: boolean,
    requiredRaceCount: integer,
    requiredRaces: Type.Array(raceEligibility),
  }),
  Type.Object({
    ...conditionCommon,
    family: Type.Literal("enhancedInteractableObject"),
    targetObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    targetSource: nullable(sourceEvidence),
    activationRequirements: requirementTemplate,
    deactivationRequirements: requirementTemplate,
  }),
  Type.Object({
    ...conditionCommon,
    family: Type.Literal("activeRequirement"),
    targetObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    targetSource: nullable(sourceEvidence),
    requirementSource: enumValue,
    activationRequirement: requirementTemplate,
    requirementGroupsAvailable: boolean,
    requirementGroupCount: integer,
    requirementGroups: Type.Array(requirementGroup),
    checkEveryNFrames: integer,
  }),
  Type.Object({
    ...conditionCommon,
    family: Type.Literal("timedActiveRequirement"),
    targetObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    targetSource: nullable(sourceEvidence),
    activationRequirement: requirementTemplate,
    activationDurationSeconds: number,
  }),
  Type.Object({
    ...conditionCommon,
    family: Type.Literal("disableRequirement"),
    targetObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    targetSource: nullable(sourceEvidence),
    activationRequirement: requirementTemplate,
  }),
]);

const unsupportedSource = Type.Union([
  Type.Object({
    source: sourceEvidence,
    family: Type.Literal("randomActivator"),
    disposition: Type.Literal("unsupported"),
    targetCount: integer,
    numberToEnable: integer,
    targets: Type.Array(Type.Union([Type.Object({ sourceFieldPath: text, name: text, source: sourceEvidence, activeSelf: boolean, activeInHierarchy: boolean }), actionUnavailable])),
    reason: text,
  }),
  Type.Object({
    source: sourceEvidence,
    family: Type.Literal("interactiveZone"),
    disposition: Type.Literal("unsupported"),
    uiElement: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    reason: text,
  }),
  Type.Object({
    source: sourceEvidence,
    family: Type.Literal("heroicConsole"),
    disposition: Type.Literal("unsupported"),
    role: text,
    roles: Type.Array(text),
    maxInteractionDistance: number,
    uiOffsetY: number,
    activeVisualObject: nullable(Type.Object({ name: text, activeSelf: boolean, activeInHierarchy: boolean })),
    reason: text,
  }),
]);
const mapZone = Type.Object({
  source: sourceEvidence,
  disposition: text,
  zoneID: integer,
  map: nullable(Type.Object({ name: text, width: integer, height: integer, dimension: integer, textureType: text })),
  boxCollider: nullable(Type.Object({ center: Type.Object({ x: number, y: number, z: number }), size: Type.Object({ x: number, y: number, z: number }), boundsCenter: Type.Object({ x: number, y: number, z: number }), boundsExtents: Type.Object({ x: number, y: number, z: number }) })),
  calibration: nullable(Type.Object({ center: Type.Object({ x: number, y: number, z: number }), extents: Type.Object({ x: number, y: number }), size: Type.Object({ x: number, y: number }), rotation: number })),
  calibrationError: nullableText,
  captureBoundsValidated: boolean,
  captureBoundsNote: text,
});
const region = Type.Object({
  source: sourceEvidence,
  disposition: text,
  regionShape: enumValue,
  regionTemplate: nullable(canonicalReference),
  regionTemplateProjection: nullable(Type.Object({})),
  captureBoundsValidated: boolean,
});
// One of the game's own world map icons, as authored in the scene. iconKind names the sprite's
// meaning; "quest", "worldQuest", and "player" icons are runtime state, not places.
export const MAP_ICON_KINDS = ["town", "fort", "camp", "dungeon", "challengeStone", "quest", "worldQuest", "player", "other"] as const;
const mapIcon = Type.Object({
  source: sourceEvidence,
  disposition: Type.Literal("extracted"),
  iconKind: Type.Union(MAP_ICON_KINDS.map(kind => Type.Literal(kind))),
  sprite: nullable(text),
  title: nullable(text),
  description: nullable(text),
  mapIconType: Type.Object({ value: integer, name: text }),
  position: Type.Object({ x: number, y: number, z: number }),
});
export type WorldMapIcon = Static<typeof mapIcon>;
const diagnostic = Type.Object({
  kind: text,
  detail: text,
  sourceFieldPath: Type.Optional(text),
  source: Type.Optional(sourceEvidence),
});
const sourceTotals = Type.Object({
  oreSpawners: integer,
  interactableObjects: integer,
  interactableTriggers: integer,
  storageContainers: integer,
  interactiveNodes: integer,
  chests: integer,
  worldQuestZones: integer,
  questScenePortals: integer,
  dungeonEntranceTriggers: integer,
  craftingStations: integer,
  propertyForSaleSigns: integer,
  corruptionAltars: integer,
  heroicConsoles: integer,
  characterGraveyards: integer,
  enhancedInteractableObjects: integer,
  activeRequirements: integer,
  timedActiveRequirements: integer,
  disableRequirements: integer,
  randomActivators: integer,
  interactiveZones: integer,
  mapZones: integer,
  regions: integer,
  mapIcons: integer,
});
const exportedTotals = Type.Object({
  resourceProducers: integer,
  interactions: integer,
  containers: integer,
  questZones: integer,
  transitions: integer,
  services: integer,
  conditionSources: integer,
  unsupportedSources: integer,
  mapZones: integer,
  regions: integer,
  mapIcons: integer,
});

export const WorldSourcesSchema = Type.Object({
  schemaVersion: Type.Literal("compendium.world-sources.v7"),
  coverage: Type.Object({
    scope: text,
    fullGameCoverage: boolean,
    includesInactiveComponents: boolean,
    authoredCandidatesWithoutInstantiation: boolean,
    authoredCandidatesWithoutRolling: boolean,
    runtimeInstanceIdsOnlyObservation: boolean,
    componentIndexSemantics: Type.Literal("all-gameobject-components"),
    traversalPerformed: boolean,
    mapZoneCaptureBoundsValidated: boolean,
    sourceSceneNativeIdRule: text,
    unsupportedFamiliesRemainVisible: boolean,
    sourceDispositionVocabulary: Type.Array(text),
    note: text,
  }),
  nativeNamingUncertainties: Type.Array(text),
  resourceProducers: Type.Array(resourceProducer),
  interactions: Type.Array(interaction),
  containers: Type.Array(Type.Union([container, storageContainer])),
  questZones: Type.Array(questZone),
  transitions: Type.Array(transition),
  mapZones: Type.Array(mapZone),
  regions: Type.Array(region),
  mapIcons: Type.Array(mapIcon),
  services: Type.Array(service),
  conditionSources: Type.Array(conditionSource),
  unsupportedSources: Type.Array(unsupportedSource),
  totals: Type.Object({ source: sourceTotals, exported: exportedTotals, unresolved: integer }),
  unresolved: Type.Array(diagnostic),
});
export type WorldSources = Static<typeof WorldSourcesSchema>;
